### ISSUE TITLE
Polarity/Negation: compare cTAKES and cNLP Transformer negation accuracy. 

### ISSUE THREAD

**Issue by comorbidity** [comorbidity/ctakes-client-python#2]
See setup.rst for running cTAKES and cNLP side by side

https://github.com/comorbidity/ctakes-client-python/blob/main/README/setup.rst

TODO: create a simple test to compare polarity "answers".
We will then review the answers together and make a decision on which negation model is better.

**Comment by mikix** [comment]
Moved to new repo
