### ISSUE TITLE
test suite failing due to known issues

### ISSUE THREAD

**Issue by comorbidity** [comorbidity/ctakes-client-python#5]
known issues: 
covid symptoms do not include all of the expected synonyms
fhirclient possibly out of date for JSON spec of FHIR resources 
http post to server requires a server to be online and configured (expected).

**Comment by mikix** [comment]
Hey! Don't make more issues here.  :grin:  Go to https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py instead

**Comment by mikix** [comment]
Landed fix in the new repo
