### ISSUE TITLE
COVID Symptoms dictionary is missing medical synonyms like "SOB" (Shortness of breath)

### ISSUE THREAD

**Issue by comorbidity** [comorbidity/ctakes-client-python#6]
In medical review: true synonyms definitions for COVID19 symptoms.

**Comment by mikix** [comment]
Hey! Don't make more issues here.  :grin:  Go to https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py instead

**Comment by mikix** [comment]
Moved to new repo
